### ISSUE TITLE
linear-gradient abnormal color

### ISSUE THREAD

**Issue by haocong** [karellodewijk/canvas-webgl#2]
![image](https://user-images.githubusercontent.com/7336914/140317978-e6f2e03a-2cff-41e4-ab04-b892e4013f2d.png)
![image](https://user-images.githubusercontent.com/7336914/140318386-f5a40f47-f616-4fdf-b46b-8aa8ec4117a1.png)

I was testing linear gradient api examples and found there was an abnormal color issue，I am wandering if the computation of gradient was wrong.

**Comment by karellodewijk** [comment]
You are right, I miscalculated the R component of color for the vertices of the gradiant, should be fixed now.
